## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a = [10, 20, 30]

b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [3]:
output_1 = [a, b]
print(output_1)

[[10, 20, 30], [30, 60, 90]]


In [4]:
output_2 = a + b
print(output_2)

[10, 20, 30, 30, 60, 90]


In [12]:
output_3 = [a[0]] + a[1:-1] + b[1:]
print(output_3)

[10, 20, 60, 90]


In [9]:
output_4 = [a[1], a[1] * 2, b[1]]
print(output_4)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [17]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

sums_of_lists = [sum(sublist) for sublist in G]

print(sums_of_lists)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [34]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [36]:
words = s.split()  
new_string = ' '.join(words[5:7]+ [words[-1].strip('!')+ words[-9]])
print(new_string)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [47]:
a = "Sarah earns $96500 in a year"

numeric_value = int(a.split('$')[1].split()[0])

monthly_income = numeric_value / 12

formatted_monthly_income = "${:.2f}".format(monthly_income)

final_string = a.split()[0] + " earns " + formatted_monthly_income + " monthly "

print(final_string)

Sarah earns $8041.67 monthly 


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [48]:
    # Create dictionaries for California and New York
CA = {
    'name': 'California',
    'pop_density': 239.1,
    'race': {'White': 0.57, 'African American': 0.06, 'Asian': 0.13, 'Other': 0.22},
    'tenure': {'Owners': 7035371, 'Renters': 5542127}
}

NY = {
    'name': 'New York',
    'pop_density': 411.2,
    'race': {'White': 0.65, 'African American': 0.15, 'Asian': 0.07, 'Other': 0.22},
    'tenure': {'Owners': 3897837, 'Renters': 3419918}
}

# Combine dictionaries into a nested dictionary
states = {'CA': CA, 'NY': NY}

# Check if Texas is in the state dictionary
print("Is Texas in the state dictionary?", 'TX' in states)

# Print the White population in New York as a percentage
white_percentage_NY = NY['race']['White'] * 100
print("White population in New York as a percentage:", white_percentage_NY)

# Update the White population fraction of NY to 0.64
NY['race']['White'] = 0.64

# Print the percentage again to verify the update
white_percentage_NY_updated = NY['race']['White'] * 100
print("Updated White population in New York as a percentage:", white_percentage_NY_updated)

# Print the percentage of households that are renters in California, with two decimal places
renter_percentage_CA = (CA['tenure']['Renters'] / (CA['tenure']['Owners'] + CA['tenure']['Renters'])) * 100
print("Percentage of households that are renters in California:", "{:.2f}".format(renter_percentage_CA))


Is Texas in the state dictionary? False
White population in New York as a percentage: 65.0
Updated White population in New York as a percentage: 64.0
Percentage of households that are renters in California: 44.06


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [23]:
import numpy as np

a = np.full((4, 4), 3)
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [25]:
b = np.random.rand(4, 4)
print(b)

[[0.85163771 0.0797379  0.96555108 0.15837614]
 [0.18456036 0.68147132 0.46140356 0.33589465]
 [0.05710962 0.4008358  0.21491094 0.60262157]
 [0.86658595 0.49688534 0.90244311 0.09206274]]


In [26]:
c = np.divide(a, b)
print(c)

[[ 3.52262467 37.62326446  3.10703395 18.94224748]
 [16.25484452  4.40223956  6.50190036  8.9313719 ]
 [52.53055475  7.48436138 13.95927048  4.97824866]
 [ 3.4618609   6.03761026  3.32430928 32.58647249]]


In [27]:
print("\nStatistics of c:")
print("Min:", np.min(c))
print("Mean:", np.mean(c))
print("Max:", np.max(c))
print("Median:", np.median(c))
print("90th percentile:", np.percentile(c, 90))


Statistics of c:
Min: 3.107033950696911
Mean: 13.978013443103428
Max: 52.53055475481926
Median: 6.993130868141344
90th percentile: 35.10486847512732


In [28]:
sum_second_column = np.sum(c[:, 1])
print("\nSum of the second column in c:", sum_second_column)


Sum of the second column in c: 55.54747565458002
