## Assignment 1 | Data Types

## Xihan is an auditing student, he coded, tested and answered these questions with ChatGPT

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a = [10, 20, 30]
b = [30, 60, 90]
print (a)
print (b)

[10, 20, 30]
[30, 60, 90]


In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [3]:
combined_list = [a, b]
print(combined_list)

[[10, 20, 30], [30, 60, 90]]


In [4]:
combined_list = a + b
print(combined_list)

[10, 20, 30, 30, 60, 90]


In [11]:
# Combine lists a and b
combined_list = a + b

# Create a list of unique elements
unique_elements_list = []

for element in combined_list:
    if (element not in a) or (element not in b):
        unique_elements_list.append(element)

print(unique_elements_list)

[10, 20, 60, 90]


In [6]:
result_list = []
for i in range(len(a)):
    result_list.append(b[i] - a[i])

print(result_list)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [12]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

sums_list = [sum(sub_list) for sub_list in G]

print(sums_list)

[30, 32, 34, 34]


In [13]:
# with a function and can be applied to all lists
def calculate_sums(list_of_lists):
    sums_list = []

    for sub_list in list_of_lists:
        sub_list_sum = sum(sub_list)
        sums_list.append(sub_list_sum)

    return sums_list

G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

sums_list = calculate_sums(G)

print(sums_list)


[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [ ]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [24]:
word_list = []

for word in s.split():
    if word[-1] in ',.!?':
        word_list.append(word[:-1])
        word_list.append(word[-1])
    else:
        word_list.append(word)

print(word_list)

['Now', 'is', 'the', 'time', 'for', 'all', 'good', 'men', 'to', 'come', 'to', 'the', 'aid', 'of', 'their', 'country', '!']


In [35]:
generated_string = word_list[5] +" "+ word_list[6]+" "+ word_list[-2] + word_list[7]
print (generated_string)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [36]:
a = "Sarah earns $96500 in a year"

In [49]:
amount_year = int(a.split("$")[1].split()[0])
amount_monthly = amount_year / 12
monthly_string = "{:.2f}".format(amount_monthly)
final_string = "Sarah earns $" + monthly_string + " monthly"
print (a.split("$"))
print (a.split("$")[1])
print (a.split("$")[1].split()[0])
print (type(a.split("$")[1].split()[0]))
print (amount_year)
print (type(amount_year))
print (final_string)

['Sarah earns ', '96500 in a year']
96500 in a year
96500
<class 'str'>
96500
<class 'int'>
Sarah earns $8041.67 monthly


In [50]:
final_string = "Sarah earns $" + "{:.2f}".format(int(a.split("$")[1].split()[0]) / 12) + " monthly"
print (final_string)

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [62]:
    # California Dictionary
ca_dict = {
    'name': 'California',
    'population_density': 239.1,
    'race': {
        'white': 0.57,
        'african_american': 0.06,
        'asian': 0.13,
        'other': 0.22
    },
    'tenure': {
        'owners': 7035371,
        'renters': 5542127
    }
}

# New York Dictionary
ny_dict = {
    'name': 'New York',
    'population_density': 411.2,
    'race': {
        'white': 0.65,
        'african_american': 0.15,
        'asian': 0.07,
        'other': 0.22
    },
    'tenure': {
        'owners': 3897837,
        'renters': 3419918
    }
}

In [53]:
# Combine Dictionaries
states = {
    'CA': ca_dict,
    'NY': ny_dict
}
print (states)

{'CA': {'name': 'California', 'population_density': 239.1, 'race': {'white': 0.57, 'african_american': 0.06, 'asian': 0.13, 'other': 0.22}, 'tenure': {'owners': 7035371, 'renters': 5542127}}, 'NY': {'name': 'New York', 'population_density': 411.2, 'race': {'white': 0.65, 'african_american': 0.15, 'asian': 0.07, 'other': 0.22}, 'tenure': {'owners': 3897837, 'renters': 3419918}}}


In [55]:
is_texas_in_states = 'TX' in states
print (is_texas_in_states)

False


In [61]:
# Update White population fraction for NY
states['NY']['race']['white'] = 0.64
print (str(states['NY']['race']['white'] * 100)+"%")

64.0%


In [67]:
ratio = states['CA']['tenure']['renters']/(states['CA']['tenure']['renters']+states['CA']['tenure']['owners'])
# Convert the ratio to a percentage with 2 decimal points
percentage = "{:.2f}%".format(ratio * 100)
print (percentage)

44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [69]:
import numpy as np

# Create a 4x4 array with all values set to 3
a = np.full((4, 4), 3)

# Print the array
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [71]:
# Create a 4x4 array with elements drawn from a uniform random distribution
b = np.random.rand(4, 4)

# Print the array
print(b)

[[0.16838338 0.77699831 0.26432588 0.15197017]
 [0.8499197  0.71815085 0.18824691 0.08442522]
 [0.93363462 0.49701478 0.89779681 0.86930027]
 [0.84557399 0.20326784 0.83095257 0.38279544]]


In [73]:
# Divide array a by array b to create array c
c = np.divide(a, b)
print(c)

[[17.81648473  3.86101226 11.34962663 19.74071645]
 [ 3.52974521  4.17739533 15.9365167  35.53440714]
 [ 3.21324846  6.0360378   3.34151331  3.45105149]
 [ 3.54788588 14.75885185  3.61031439  7.83708394]]


In [75]:
# Compute and print statistics of array c rounded to two decimal points
c_min = round(np.min(c), 2)
c_mean = round(np.mean(c), 2)
c_max = round(np.max(c), 2)
c_median = round(np.median(c), 2)
c_percentile_90 = round(np.percentile(c, 90), 2)

print(f"Minimum value of c: {c_min}")
print(f"Mean value of c: {c_mean}")
print(f"Maximum value of c: {c_max}")
print(f"Median value of c: {c_median}")
print(f"90th percentile value of c: {c_percentile_90}")

Minimum value of c: 3.21
Mean value of c: 9.86
Maximum value of c: 35.53
Median value of c: 5.11
90th percentile value of c: 18.78


In [76]:
# Compute and print the sum of the second column in array c
sum_second_column = np.sum(c[:, 1])
print (sum_second_column)

28.83329723816869
