## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [118]:
a= [10,20,30]
b= [30,60,90]
b

[30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [119]:
[a,b]

[[10, 20, 30], [30, 60, 90]]

In [120]:
[a+b]

[[10, 20, 30, 30, 60, 90]]

In [121]:
[a[0],a[1],b[1],b[2]]

[10, 20, 60, 90]

In [122]:
[a[1],b[1]-20,b[1]]

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [123]:
a=[13,9,8]
b=[14,6,12]
c=[10,13,11]
d=[7,18,9]
G=[sum(a),sum(b),sum(c),sum(d)]
G

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [124]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [125]:
w = s[20:29]+"countrymen"
print(w)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [176]:
a = "Sarah earns $96500 in a year"
monthly_salary = "{:.2f}".format(int(a.split("$")[1].split()[0]) / 12)
print("Sarah earns $" + monthly_salary + " monthly")

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [197]:
def Merge(CA, NY): 
    res = CA | NY
    return res 

CA= {'name': 'california', 'pop_density': '239.1', 'race': {'prop white':'0.57','prop afr amer':'0.06','prop asian':'0.13','prop other':'0.22'},'tenure':{'owners':7035371,'renters':5542127}}
NY= {'name': 'new york', 'pop_density': '411.2', 'race': {'prop white':0.65,'prop afr amer':'0.15','prop asian':'0.07','prop other':'0.22'},'tenure':{'owners':3897837,'renters':3419918}}
states = Merge(CA, NY) 
print(states)

{'name': 'new york', 'pop_density': '411.2', 'race': {'prop white': 0.65, 'prop afr amer': '0.15', 'prop asian': '0.07', 'prop other': '0.22'}, 'tenure': {'owners': 3897837, 'renters': 3419918}}


In [198]:
some = "Texas"

if some in states.values():
    print('exists!')
else:
    print("doesn't exist!")

doesn't exist!


In [199]:
x = NY['race']['prop white']*100
print("White population percentage in New York:",x, "%")

White population percentage in New York: 65.0 %


In [200]:
NY['race']['prop white'] = 0.64
z = NY['race']['prop white']*100
print("White population percentage in New York:",z, "%")

White population percentage in New York: 64.0 %


In [202]:
renters_percentage_CA = (CA["tenure"]["renters"] / (CA["tenure"]["owners"] + CA["tenure"]["renters"])) * 100
print("Percentage of households that are renters in California:", "{:.2f}".format(renters_percentage_CA), "%")

Percentage of households that are renters in California: 44.06 %


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [157]:
import numpy as np
a = np.full((4, 4), 3)

In [159]:
b = np.random.rand(4, 4)
print(b)

[[0.63808175 0.45288615 0.95722431 0.69602308]
 [0.64832559 0.13803027 0.97495713 0.96976116]
 [0.61108429 0.26929256 0.69369243 0.15042151]
 [0.48420148 0.62392704 0.23728741 0.80480466]]


In [161]:
c = np.divide(a, b)
print(c)

[[ 4.70159193  6.62418137  3.13406163  4.31020189]
 [ 4.62730465 21.73436374  3.07705838  3.09354523]
 [ 4.90930638 11.1403005   4.3246832  19.94395656]
 [ 6.19576793  4.80825448 12.64289568  3.72761259]]


In [162]:
print("Minimum value:", np.min(c))
print("Mean value:", np.mean(c))
print("Maximum value:", np.max(c))
print("Median value:", np.median(c))
print("90th percentile value:", np.percentile(c, 90))

Minimum value: 3.077058380567783
Mean value: 7.437192884845382
Maximum value: 21.73436373726625
Median value: 4.754923207184648
90th percentile value: 16.29342611944285


In [163]:
sum_second_column = np.sum(c[:, 1])
print("Sum of the second column in array c:", sum_second_column)

Sum of the second column in array c: 44.30710008979213
