## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
# list containing the numbers 10, 20, and 30
a = [10, 20, 30]

# list containing the numbers 30, 60, and 90 
b = [30, 60, 90]

In [3]:
print("List a:", a)

List a: [10, 20, 30]


In [4]:
print ("List b:", b)

List b: [30, 60, 90]


In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [5]:
output1 = [a, b]

In [15]:
print ("Output 1:", output1)

Output 1: [[10, 20, 30], [30, 60, 90]]


In [7]:
output2 = a + b

In [14]:
print ("Output 2:", output2)

Output 2: [10, 20, 30, 30, 60, 90]


In [11]:
output3 = [a[0], a[1],b[1], b[2]]

In [12]:
print ("Output 3:", output3)

Output 3: [10, 20, 60, 90]


In [16]:
output4 = [a[1]*2, b[1]*2, b[2]*2]
print("Output 4:", output4)

Output 4: [40, 120, 180]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [17]:
# list
G = [[13, 9, 8], [14, 6, 12], [10,13,11], [7, 18, 9]]

In [20]:
sums_list = []

for sublist in G: 
    sublist_sum = sum(sublist)
    sums_list.append(sublist_sum)
print(sums_list)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [23]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [38]:
words = s.split()

In [61]:
new_string = ' '.join(words[5:7]+ [words[-1].strip('!')+ words[-9]])
print(new_string)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [1]:
# defining the variable
a = "Sarah earns $96500 in a year"

In [2]:
numeric_value = int(a.split('$')[1].split()[0])

In [3]:
monthly_income = numeric_value / 12

In [4]:
formatted_monthly_income = "${:.2f}".format(monthly_income)

In [5]:
final_string = a.split()[0] + " earns " + formatted_monthly_income + " monthly"

In [6]:
print(final_string)

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [26]:
    CA = {
    'name': 'California',
    'pop_density': 239.1,
    'race': {
        'White': 0.57,
        'African American': 0.06,
        'Asian': 0.13,
        'Other': 0.22
    },
    'tenure': {
        'Owners': 7035371,
        'Renters': 5542127
    }
}

NY = {
    'name': 'New York',
    'pop_density': 411.2,
    'race': {
        'White': 0.65,
        'African American': 0.15,
        'Asian': 0.07,
        'Other': 0.22
    },
    'tenure': {
        'Owners': 3897837,
        'Renters': 3419918
    }
}


In [22]:
states = {
    'CA': CA,
    'NY': NY
}

In [28]:
print("Is Texas in state dictionary?")
print('TX' in states)

Is Texas in state dictionary?
False


In [38]:
ny_white_percentage = NY['race']['White'] * 100
print(f"The White population in New York is {ny_white_percentage:.2f}%")


The White population in New York is 64.00%


In [30]:
NY['race']['White'] = 0.64

In [39]:
ny_white_percentage_updated = NY['race']['White'] * 100
print(f"After the update, the White population in New York is now {ny_white_percentage_updated:.2f}%")


After the update, the White population in New York is now 64.00%


In [54]:
ca_renters_percentage = (CA['tenure']['Renters'] / (CA['tenure']['Owners'] + CA['tenure']['Renters'])) * 100
print(f"The percentage of households that are renters in California is {ca_renters_percentage:.2f}%")

The percentage of households that are renters in California is 44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [59]:
import numpy as np

In [60]:
a = np.full((4, 4), 3)
print("Array a:")
print(a)

Array a:
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [61]:
b = np.random.rand(4, 4)
print("\nArray b:")
print(b)


Array b:
[[0.34582849 0.60938991 0.41546057 0.82087296]
 [0.69722422 0.15942327 0.13348468 0.8513435 ]
 [0.63012152 0.14093807 0.24462346 0.84642763]
 [0.67867485 0.21414796 0.49601143 0.74546115]]


In [62]:
c = np.divide(a, b)
print("\nArray c:")
print(c)


Array c:
[[ 8.67482029  4.92295644  7.22090189  3.65464591]
 [ 4.30277653 18.81783007 22.47448997  3.52384202]
 [ 4.76098642 21.28594556 12.2637463   3.54430773]
 [ 4.42037893 14.00900559  6.04824769  4.02435457]]


In [63]:
c_min = np.min(c)
c_mean = np.mean(c)
c_max = np.max(c)
c_median = np.median(c)
c_90th_percentile = np.percentile(c, 90)
print("\nStatistics of array c:")
print(f"Min: {c_min}, Mean: {c_mean}, Max: {c_max}, Median: {c_median}, 90th Percentile: {c_90th_percentile}")


Statistics of array c:
Min: 3.5238420151079035, Mean: 8.99682724259036, Max: 22.474489970727173, Median: 5.485602060809478, 90th Percentile: 20.05188781363053


In [64]:
c_second_column_sum = np.sum(c[:, 1])
print(f"\nSum of the second column in array c: {c_second_column_sum}")



Sum of the second column in array c: 59.03573765172488
