## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a = [10, 20, 30]
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [4]:
[a, b]

[[10, 20, 30], [30, 60, 90]]

In [5]:
a+b

[10, 20, 30, 30, 60, 90]

In [6]:
[a[0], a[1]] + b[1:]

[10, 20, 60, 90]

In [20]:
[a[1], a[1] * 2, b[1]]

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [3]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
sums_of_lists = [sum(sublist) for sublist in G]

print(sums_of_lists)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [30]:
s = 'Now is the time for all good men to come to the aid of their country!'

Now is the time for all good men to come to the aid of their country!


In [41]:
s = 'Now is the time for all good men to come to the aid of their country!'
a = s.split(" ")[5:8]
a[a.index('men')] = 'countrymen'
s = ' '.join(a)
print(s)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [50]:
a = "Sarah earns $96500 in a year"
salary_str = a.split('$')[1].split()[0]
salary = float(salary_str)
monthly_salary = salary / 12
result_string = f"Sarah earns ${monthly_salary:.2f} monthly"
print(result_string)

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [52]:
# Creating dictionaries for California and New York
CA = {
    'name': 'California',
    'pop_density': 239.1,
    'race': {
        'Prop White': 0.57,
        'Prop Afr Amer': 0.06,
        'Prop Asian': 0.13,
        'Prop Other': 0.22
    },
    'tenure': {
        'Owners': 7035371,
        'Renters': 5542127
    }
}

NY = {
    'name': 'New York',
    'pop_density': 411.2,
    'race': {
        'Prop White': 0.65,
        'Prop Afr Amer': 0.15,
        'Prop Asian': 0.07,
        'Prop Other': 0.22
    },
    'tenure': {
        'Owners': 3897837,
        'Renters': 3419918
    }
}

# Combining dictionaries into a nested dictionary called "states"
states = {
    'CA': CA,
    'NY': NY
}

# Check if Texas is in our state dictionary
print("Is Texas in our state dictionary?")
print('TX' in states)

# Print the White population in New York as a percentage
ny_white_percentage = NY['race']['Prop White'] * 100
print("White population percentage in New York:", ny_white_percentage, "%")

# Assume there was a typo in the data, and update the White population fraction of NY to 0.64
NY['race']['Prop White'] = 0.64

# Verify that it was updated by printing the percentage again
ny_white_percentage_updated = NY['race']['Prop White'] * 100
print("Updated White population percentage in New York:", ny_white_percentage_updated, "%")

# Print the percentage of households that are renters in California, with two decimal places
ca_renter_percentage = (CA['tenure']['Renters'] / (CA['tenure']['Owners'] + CA['tenure']['Renters'])) * 100
print("Percentage of households that are renters in California: {:.2f}%".format(ca_renter_percentage))


Is Texas in our state dictionary?
False
White population percentage in New York: 65.0 %
Updated White population percentage in New York: 64.0 %
Percentage of households that are renters in California: 44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [54]:
import numpy as np
a = np.full((4, 4), 3)
print("Array 'a':")
print(a)
print()


Array 'a':
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]



In [55]:
b = np.random.rand(4, 4)
print("Array 'b':")
print(b)
print()

Array 'b':
[[0.51292069 0.75655566 0.23062292 0.14970112]
 [0.23819805 0.96818997 0.72648554 0.8086697 ]
 [0.57136052 0.76053204 0.23689916 0.82873898]
 [0.4804497  0.93269733 0.93075355 0.36367352]]



In [56]:
c = a / b
print("Array 'c' (a divided by b):")
print(c)
print()

Array 'c' (a divided by b):
[[ 5.84885747  3.96533947 13.00824764 20.03992977]
 [12.59456179  3.09856547  4.12946966  3.70979645]
 [ 5.25062533  3.94460699 12.66361604  3.61995765]
 [ 6.24415004  3.21647753  3.22319478  8.24915712]]



In [57]:
print("Statistics of array 'c':")
print("Min:", np.min(c))
print("Mean:", np.mean(c))
print("Max:", np.max(c))
print("Median:", np.median(c))
print("90th Percentile:", np.percentile(c, 90))
print()

Statistics of array 'c':
Min: 3.0985654731826644
Mean: 7.050409575833529
Max: 20.03992977477668
Median: 4.690047496531097
90th Percentile: 12.835931838081883



In [58]:
sum_second_column = np.sum(c[:, 1])
print("Sum of the second column in array 'c':", sum_second_column)

Sum of the second column in array 'c': 14.224989462496012
