## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [5]:
a = [10,20,30]

b = [30,60,90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [6]:
list = [a,b]
list

[[10, 20, 30], [30, 60, 90]]

In [8]:
a+b

[10, 20, 30, 30, 60, 90]

In [12]:
list2 = a[:2]+b[1:]
list2

[10, 20, 60, 90]

In [19]:
list3 = [x*2 for x in a]
list3

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [24]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
list_sum = [sum(sublist) for sublist in G]
list_sum

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [28]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [55]:
s2 = s.split()
print(s2)

['Now', 'is', 'the', 'time', 'for', 'all', 'good', 'men', 'to', 'come', 'to', 'the', 'aid', 'of', 'their', 'country!']


In [63]:
a = s2[5:7]
a

['all', 'good']

In [66]:
b = s2[7]
b

'men'

In [67]:
c = s2[15]
c = c.strip('!')
c

'country'

In [72]:
d = c+b
d

'countrymen'

In [73]:
a.insert(2, d)
a

['all', 'good', 'countrymen']

In [74]:
output = ' '.join(a)
output

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [77]:
a = "Sarah earns $96500 in a year"

In [81]:
a.split()[2]

'$96500'

In [84]:
(a.split()[2])[1:]

'96500'

In [87]:
int((a.split()[2])[1:])

96500

In [88]:
int((a.split()[2])[1:])/12

8041.666666666667

In [90]:
round(int((a.split()[2])[1:])/12,2)

8041.67

In [92]:
str(round(int((a.split()[2])[1:])/12,2))

'8041.67'

In [93]:
new_a = "Sarah earns $" + str(round(int((a.split()[2])[1:])/12,2)) + " monthly"
print(new_a)

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

### Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York. Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

In [106]:
CA_race_keys = ['white','afr amer','asian','other']

In [107]:
CA_race_values = [0.57, 0.06, 0.13, 0.22]

In [109]:
CA_race = dict(zip(CA_race_keys, CA_race_values))
print(CA_race)

{'white': 0.57, 'afr amer': 0.06, 'asian': 0.13, 'other': 0.22}


In [111]:
NY_race_keys = ['white','afr amer','asian','other']

In [112]:
NY_race_values = [0.65, 0.15, 0.07, 0.22]

In [113]:
NY_race = dict(zip(NY_race_keys, NY_race_values))
print(NY_race)

{'white': 0.65, 'afr amer': 0.15, 'asian': 0.07, 'other': 0.22}


In [114]:
CA_tenure = {}

In [116]:
CA_tenure.update({'owners': '7035371','renters': '5542127' })
print(CA_tenure)

{'owners': '7035371', 'renters': '5542127'}


In [117]:
NY_tenure = {}
NY_tenure.update({'owners': '3897837','renters': '3419918' })
print(NY_tenure)

{'owners': '3897837', 'renters': '3419918'}


In [119]:
CA_dict_keys = ['name', 'pop_density','race','tenure']

In [120]:
CA_dict_values = ['California',239.1,CA_race,CA_tenure]

In [125]:
CA = dict(zip(CA_dict_keys, CA_dict_values))
print(CA)

{'name': 'California', 'pop_density': 239.1, 'race': {'white': 0.57, 'afr amer': 0.06, 'asian': 0.13, 'other': 0.22}, 'tenure': {'owners': '7035371', 'renters': '5542127'}}


In [126]:
NY_dict_keys = ['name', 'pop_density','race','tenure']
NY_dict_values = ['New York',411.2,NY_race,NY_tenure]

In [127]:
NY = dict(zip(NY_dict_keys, NY_dict_values))
print(NY)

{'name': 'New York', 'pop_density': 411.2, 'race': {'white': 0.65, 'afr amer': 0.15, 'asian': 0.07, 'other': 0.22}, 'tenure': {'owners': '3897837', 'renters': '3419918'}}


In [128]:
states = {}

In [129]:
states.update({'CA': CA,'NY': NY })
print(states)

{'CA': {'name': 'California', 'pop_density': 239.1, 'race': {'white': 0.57, 'afr amer': 0.06, 'asian': 0.13, 'other': 0.22}, 'tenure': {'owners': '7035371', 'renters': '5542127'}}, 'NY': {'name': 'New York', 'pop_density': 411.2, 'race': {'white': 0.65, 'afr amer': 0.15, 'asian': 0.07, 'other': 0.22}, 'tenure': {'owners': '3897837', 'renters': '3419918'}}}


### Check if Texas is in our state dictionary (we know it isn't but show us).

In [130]:
if 'Texas' in states:
    print("Texas is in our state dictionary.")
else:
    print("Texas is not in our state dictionary.")

Texas is not in our state dictionary.


### Print the White population in New York as a percentage

In [144]:
white_percentage = "{:.2f}%".format((NY['race']['white'])*100)
white_percentage

'65.00%'

### Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

In [145]:
NY['race']['white'] = 0.64
white_percentage = "{:.2f}%".format((NY['race']['white'])*100)
white_percentage

'64.00%'

### Print the percentage of households that are renters in California, with two decimal places

In [154]:
CA_renters = int(CA['tenure']['renters'])
CA_renters

5542127

In [159]:
CA_owners = int(CA['tenure']['owners'])
CA_owners

7035371

In [160]:
CA_households = CA_renters + CA_owners
CA_households

12577498

In [162]:
renters_percentage = "{:.2f}%".format((CA_renters/CA_households)*100)
print('renters percentage in CA = ', renters_percentage)

renters percentage in CA =  44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [163]:
import numpy as np

In [164]:
a = np.full((4, 4), 3)
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [167]:
b = np.random.rand(4, 4)
print (b)

[[0.6215951  0.42188663 0.0036807  0.14435401]
 [0.73857204 0.95016949 0.64035183 0.5657084 ]
 [0.30295568 0.46032449 0.55255389 0.46876052]
 [0.51487706 0.83432537 0.61427833 0.66227537]]


In [168]:
c = np.divide(a, b)
print(c)

[[  4.8262929    7.1109151  815.06249353  20.7822426 ]
 [  4.06189221   3.15733143   4.68492453   5.30308547]
 [  9.90243866   6.51714189   5.42933472   6.39985632]
 [  5.8266337    3.59571948   4.88377968   4.52983777]]


In [173]:
print("Min of c =", np.min(c))
print("Mean of c =", np.mean(c))
print("Max of c =", np.max(c))
print("Median of c =", np.median(c))
print("90th percentile of c =", np.percentile(c, 90))

Min of c = 3.157331428155448
Mean of c = 57.00461999846215
Max of c = 815.0624935340028
Median of c = 5.366210091363328
90th percentile of c = 15.342340628603624


In [174]:
sum_second_column_c = np.sum(c[:, 1])
print("Sum of the second column in c =", sum_second_column_c)

Sum of the second column in c = 20.381107896594298
