## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [48]:
a = [10,20,30]
b = [30,60,90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [49]:
c = [a,b]
print(c)

[[10, 20, 30], [30, 60, 90]]


In [50]:
d = a + b
print(d)

[10, 20, 30, 30, 60, 90]


In [51]:
d.remove(30)
print(d)

[10, 20, 30, 60, 90]


In [52]:
e = [a[1], a[1]*2, b[1]]
print(e)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [53]:
f = [13, 9, 8]
g = [14, 6, 12]
h = [10, 13, 11]
i = [7, 18, 9]
j = [f[0]+f[1]+f[2], g[0]+g[1]+g[2], h[0]+h[1]+h[2], i[0]+i[1]+i[2]]
print(j)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [40]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [45]:
t = str.split(s, " ")
u = t[5]+" "+t[6]+" country"+t[7]
print(u)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [56]:
a = "Sarah earns $96500 in a year"
a.replace("$96500 in a year", "$8041.67 monthly")

'Sarah earns $8041.67 monthly'

### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [82]:
#Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York. 
keysrace = ['prop_white', 'prop_AA', 'prop_asian', 'prop_other']
CAracevalues = [0.57, 0.06, 0.13, 0.22]
CArace = dict(zip(keysrace, CAracevalues))
NYracevalues = [0.65, 0.15, 0.07, 0.22]
NYrace = dict(zip(keysrace, CAracevalues))
NYrace = dict(zip(keysrace, CAracevalues))
keystenure = ['owners', 'renters']
CAtenurevalues = [7035371, 5542127]
CAtenure = dict(zip(keystenure, CAtenurevalues))
NYtenurevalues = [3897837, 3419918]
NYtenure = dict(zip(keystenure, CAtenurevalues))

In [83]:
keys = ['name', 'pop_density', 'race', 'tenure']
CAvalues = ['CA', 239.1, CArace, CAtenure]
NYvalues = ['NY', 411.2, NYrace, NYtenure]
CA = dict(zip(keys, CAvalues))
NY = dict(zip(keys, NYvalues))

In [84]:
#Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.
#Check if Texas is in our state dictionary (we know it isn't but show us).
states = {'CA': CA, 'NY': NY}
states('TX')

TypeError: 'dict' object is not callable

In [85]:
#Print the White population in New York as a percentage
format(NYracevalues[0], ".0%")

'65%'

In [87]:
#Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.
NYracevalues[0] = 0.64
format(NYracevalues[0], ".0%")

'64%'

In [91]:
#Print the percentage of households that are renters in California, with two decimal places
format(CAtenurevalues[1]/(CAtenurevalues[0]+CAtenurevalues[1]), ".2%")

'44.06%'

### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [95]:
import numpy as np
a = np.ones((4, 4))*3
print(a)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [98]:
b = np.random.randint(1,20,(4,4))
print(b)

[[ 7 16 10  6]
 [10  8 12  2]
 [14  5  4  7]
 [ 3  1  9  3]]


In [99]:
c = a / b
print(c)

[[0.42857143 0.1875     0.3        0.5       ]
 [0.3        0.375      0.25       1.5       ]
 [0.21428571 0.6        0.75       0.42857143]
 [1.         3.         0.33333333 1.        ]]


In [107]:
min = np.min(c)
max = np.max(c)
median = np.median(c)
perc = np.percentile(c, 90)
print(min, ",", max, ",",median,",",perc)

0.1875 , 3.0 , 0.42857142857142855 , 1.25


In [110]:
d = np.sum(c, 0)
print(d[1])

4.1625
