## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [1]:
a = [10, 20, 30] 
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [2]:
[a, b]

[[10, 20, 30], [30, 60, 90]]

In [3]:
[a+b]

[[10, 20, 30, 30, 60, 90]]

In [6]:
a[:2] + b[1:]

[10, 20, 60, 90]

In [11]:
[a[1], a[1]*2, b[1]]

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [19]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
a = [13, 9, 8]
b = [14, 6, 12]
c = [10, 13, 11]
d = [7, 18, 9]
sum(a)
[sum(a), sum(b), sum(c), sum(d)]

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [21]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [68]:
#s[19:69]
#s[19:29] all good
#s[60:68] country
#s[29:33] men
#s[19:33] all good men
#s[19:33] + s[60:] all good men country!
#s[19:33] + s[43:44] +s[60:68]
#s[19:33]+ s[60:68] + s[43:44]
#s[60:68] + s[29:33] countrymen
s[19:29] + s[60:68] + s[29:33]



' all good  countrymen '

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [272]:
a = "Sarah earns $96500 in a year"
#print(96500/12)
#yearly_income = split_str = a.split('$')
#yearly_income = split_str = split_str[1].split()[0]
#yearly_income = str(float)
#print(yearly_income)
#type(yearly_income)
#print(yearly_income / 12)
#yearly_income = float(a.replace('$', '').split()[2])
#monthly_income = yearly_income / 12
#numerical_value = 8041.67
#result = f"Sarah earns ${monthly_income:.2f} monthly"
#print("Sarah earns ${monthly_income:.2f} monthly")
#print ("sarah earns ${numerical_value:.2f} monthly")


#I am having lots of trouble with being able to switch between data types, so am not sure how to get further than this
print("Sarah earns ${monthly_income:.2f} monthly")










Sarah earns ${monthly_income:.2f} monthly


In [205]:
### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

SyntaxError: unterminated string literal (detected at line 14) (2760750831.py, line 14)

In [229]:
CA = {"name": "California","pop_density": 239.1,"race": {"Prop White": 0.57, "Prop Afr Amer": 0.06, "Prop Asian": 0.13,"Prop Other": 0.22},
    "tenure": { "Owners": 7035371, "Renters": 5542127}}
NY = {"name": "New York", "pop_density": 411.2, "race": {"Prop White": 0.65, "Prop Afr Amer": 0.15, "Prop Asian": 0.07,"Prop Other": 0.22},
    "tenure": { "Owners": 3897837, "Renters": 3419918}}
states = {"CA": CA, "NY" : NY}
if "TX" in "states": print("TX in  dictionary")
else: print("TX not in dictionary")

TX not in dictionary


In [239]:
prop_white_ny = states["NY"]["race"]["Prop White"]
perc_white = prop_white_ny * 100
print(perc_white)

65.0


In [252]:
states["NY"]["race"]["Prop White"] = 0.64
print("Updated white population in New York: {:.0f}%".format(states["NY"]["race"]["Prop White"] * 100))

Updated white population in New York: 64%


In [263]:
renters = states["CA"]["tenure"]["Renters"]
owners = states["CA"]["tenure"]["Owners"]
renter_pct = (renters/(renters + owners)) * 100
print("Pct renters in CA: {:.2f}%".format(renter_pct))

Pct renters in CA: 44.06%


In [167]:
import numpy as np

### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [174]:
a = np.full((4,4),3)
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [178]:
b = x = np.random.rand(4,4)
print(b)

[[0.6249257  0.81170775 0.38173778 0.34217707]
 [0.25386306 0.4881675  0.60956947 0.61525507]
 [0.45062567 0.43934721 0.28297317 0.41723567]
 [0.92134323 0.49773549 0.51734858 0.32254496]]


In [184]:
c = (a/b)
c = np.divide(a, b)
print(c)

[[ 4.80057072  3.69591151  7.85879773  8.76739047]
 [11.81739464  6.14543159  4.92150629  4.87602649]
 [ 6.65741041  6.82831246 10.60171194  7.19018106]
 [ 3.25611555  6.02729773  5.79879816  9.30102897]]


In [191]:
print("min", np.min(c))
print("mean", np.mean(c))
print("max", np.max(c))
print("median", np.median(c))
print("90th Percentile", np.percentile(c, 90))


min 3.2561155476114836
mean 6.783992856616452
max 11.817394637386412
median 6.401420998547945
90th Percentile 9.951370454001779


In [192]:
print("sum of the second column", np.sum(c))

sum of the second column 108.54388570586323


In [199]:
print("sum of the second column", np.sum(c[:,1]))


sum of the second column 22.69695328863495
