## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a = [10, 20, 30]
b = [30, 60, 90]
print(a)
print(b)

[10, 20, 30]
[30, 60, 90]


In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [3]:
a,b

([10, 20, 30], [30, 60, 90])

In [4]:
a+b

[10, 20, 30, 30, 60, 90]

In [5]:
c=a[:2] + b[1:]
print(c)

[10, 20, 60, 90]


In [6]:
d = []

for num in a:
        d.append(num * 2)

print(d)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [7]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
Sum = [sum(sublist) for sublist in G]
print (Sum)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [8]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [9]:
s = s.split(" ")
part1=s[5]
part2=s[6]
part3=s[7]
part4=s[15].strip('!')+s[7]
part5=[part1, part2, part4]
newstring = ' '.join(part5)
print(newstring)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [10]:
a = "Sarah earns $96500 in a year"
salary_str = a.split()[2]
salary_float = float(salary_str.replace('$', '')) 
monthly_salary = salary_float / 12  
monthly_salary_str = "${:,.2f}".format(monthly_salary)  
print("Sarah earns", monthly_salary_str, "monthly")

Sarah earns $8,041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [13]:
#Step1
CA = {"name": "California", "pop_density": 239.1, "race": {"Prop White": 0.57, "Prop Afr Amer": 0.06, "Prop Asian": 0.13, "Prop Other": 0.22}, "tenure": {
        "Owners": 7035371,"Renters": 5542127}}
NY = {"name": "New York","pop_density": 411.2,"race": {"Prop White": 0.65, "Prop Afr Amer": 0.15, "Prop Asian": 0.07, "Prop Other": 0.22}, "tenure": {
      "Owners": 3897837,"Renters": 3419918}}
states = {"CA": CA, "NY": NY}
#Step2
print("Is Texas in our state dictionary?", "TX" in states)
#Step3
NYWhite_Percentage = NY["race"]["Prop White"] * 100
print("White population in New York:", NYWhite_Percentage, "%")
#Step4
NY["race"]["Prop White"] = 0.64
print("Updated White population in New York:", NY["race"]["Prop White"] * 100, "%")
#Step5
ca_renter_percentage = (CA["tenure"]["Renters"] / (CA["tenure"]["Owners"] + CA["tenure"]["Renters"])) * 100
print("Percentage of households that are renters in California: {:.2f}%".format(ca_renter_percentage))

Is Texas in our state dictionary? False
White population in New York: 65.0 %
Updated White population in New York: 64.0 %
Percentage of households that are renters in California: 44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [14]:
import numpy as np
array1 = np.full((4, 4), 3)
print(array1)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [15]:
array2 = np.random.rand(4, 4)
print(array2)

[[0.54889086 0.25195755 0.74062287 0.98894709]
 [0.3399089  0.22859653 0.61805081 0.17768433]
 [0.25878851 0.47606519 0.8319465  0.7080985 ]
 [0.21683814 0.60643826 0.4933931  0.07824044]]


In [16]:
array3 = np.divide(array1, array2)
print(array3)

[[ 5.46556744 11.90676758  4.05064457  3.03352933]
 [ 8.82589412 13.12355889  4.85396987 16.88387525]
 [11.59247767  6.301658    3.60600112  4.23669873]
 [13.83520469  4.94691745  6.08034449 38.34334334]]


In [18]:
parta=np.min(array3)
partb=np.mean(array3)
partc=np.max(array3)
partd=np.median(array3)
parte=np.percentile(array3, 90)
print(parta)
print(partb)
print(partc)
print(partd)
print(parte)

3.03352932693433
9.817903284172326
38.34334333671482
6.191001246029608
15.359539970740137


In [19]:
second_column_sum = np.sum(array3[:, 1])
print("Sum of the second column in c:", second_column_sum)

Sum of the second column in c: 36.27890192644668
