## Assignment 1 | Data Types

Add code cells as needed for your answers. 

UCB_CYPLAN255_Spring_2024

Jeremy Chen

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [1]:
a = [10, 20, 30]
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [2]:
combined_lists_1 = [a, b]
print(combined_lists_1)

[[10, 20, 30], [30, 60, 90]]


In [3]:
combined_lists_2 = a + b
print(combined_lists_2)

[10, 20, 30, 30, 60, 90]


In [4]:
combined_lists_3 = [a[0], a[1], b[1], b[2]]
print(combined_lists_3)

[10, 20, 60, 90]


In [5]:
combined_lists_4 = [a[1], a[1]*2, b[1]]
print(combined_lists_4)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [6]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
sum_lists = [sum(G[0]), sum(G[1]), sum(G[2]), sum(G[3])]
print(sum_lists)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [7]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [8]:
s_countrymen = s.replace('men', 'countrymen')
result = ' '.join(s_countrymen.split()[5:8])
print(result)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [9]:
a = "Sarah earns $96500 in a year"
print(a.replace('96500 in a year', '8041.67 monthly'))

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

#### Q1:
Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York. Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

In [10]:
CA = {
    'name': 'California',
    'pop_density': 239.1,
    'race': {
        'White': 0.57,
        'Afr Amer': 0.06,
        'Asian': 0.13,
        'Other': 0.22
    },
    'tenure': {
        'Owners': 7035371,
        'Renters': 5542127
    }
}

NY = {
    'name': 'New York',
    'pop_density': 411.2,
    'race': {
        'White': 0.65,
        'Afr Amer': 0.15,
        'Asian': 0.07,
        'Other': 0.22
    },
    'tenure': {
        'Owners': 3897837,
        'Renters': 3419918
    }
}

print(CA)
print(NY)

{'name': 'California', 'pop_density': 239.1, 'race': {'White': 0.57, 'Afr Amer': 0.06, 'Asian': 0.13, 'Other': 0.22}, 'tenure': {'Owners': 7035371, 'Renters': 5542127}}
{'name': 'New York', 'pop_density': 411.2, 'race': {'White': 0.65, 'Afr Amer': 0.15, 'Asian': 0.07, 'Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}


In [11]:
states = {'CA': CA, 'NY': NY}
print(states)

{'CA': {'name': 'California', 'pop_density': 239.1, 'race': {'White': 0.57, 'Afr Amer': 0.06, 'Asian': 0.13, 'Other': 0.22}, 'tenure': {'Owners': 7035371, 'Renters': 5542127}}, 'NY': {'name': 'New York', 'pop_density': 411.2, 'race': {'White': 0.65, 'Afr Amer': 0.15, 'Asian': 0.07, 'Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}}


#### Q2:
Check if Texas is in our state dictionary (we know it isn't but show us).

In [12]:
is_texas_in_state_dict = 'TX' in states
print(f"Is Texas in the state dictionary? {is_texas_in_state_dict}")

Is Texas in the state dictionary? False


#### Q3:
Print the White population in New York as a percentage

In [13]:
white_percentage_NY = NY['race']['White'] * 100
print(f"White population in New York: {white_percentage_NY:.2f}%")

White population in New York: 65.00%


#### Q4: 
Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

In [14]:
NY['race']['White'] = 0.64
white_percentage_NY = NY['race']['White'] * 100
print(f"White population in New York: {white_percentage_NY:.2f}%")

White population in New York: 64.00%


#### Q5:
Print the percentage of households that are renters in California, with two decimal places

In [15]:
renters_percentage_CA = (CA['tenure']['Renters'] / (CA['tenure']['Owners'] + CA['tenure']['Renters'])) * 100
print(f"Percentage of households that are renters in California: {renters_percentage_CA:.2f}%")

Percentage of households that are renters in California: 44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [16]:
import numpy as np

#### Q1:

In [17]:
a = np.full((4, 4), 3)
print("Array 'a':")
print(a)

Array 'a':
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


#### Q2:

In [18]:
b = np.random.rand(4, 4)
print("Array 'b':")
print(b)

Array 'b':
[[0.76233377 0.58126606 0.05340594 0.14625254]
 [0.20802076 0.99311866 0.44891886 0.34503167]
 [0.48596339 0.47634628 0.28668924 0.80495489]
 [0.4960993  0.59985479 0.62265659 0.30293855]]


#### Q3:

In [19]:
c = np.divide(a, b)
print("Array 'c' (Array 'a' divided by Array 'b'):")
print(c)

Array 'c' (Array 'a' divided by Array 'b'):
[[ 3.93528415  5.16114769 56.17352169 20.51246469]
 [14.42163733  3.02078706  6.68272208  8.69485402]
 [ 6.17330452  6.2979394  10.46429226  3.72691694]
 [ 6.0471764   5.00121034  4.81806513  9.90299852]]


#### Q4:
Compute and print the min, mean, max, median, and 90th percentile values of c

In [20]:
print(f"Min of c: {np.min(c)}")
print(f"Mean of c: {np.mean(c)}")
print(f"Max of c: {np.max(c)}")
print(f"Median of c: {np.median(c)}")
print(f"90th percentile of c: {np.percentile(c, 90)}")

Min of c: 3.0207870581527683
Mean of c: 10.689645138296722
Max of c: 56.17352168754408
Median of c: 6.235621959348967
90th percentile of c: 17.467051011641185


#### Q5:
Compute and print the sum of the second column in c

In [21]:
print(c[:, 1])
sum_second_column_c = np.sum(c[:, 1])
print(f"Sum of the second column in c: {sum_second_column_c}")

[5.16114769 3.02078706 6.2979394  5.00121034]
Sum of the second column in c: 19.48108448330599
