## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a = [10, 20, 30]
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [3]:
# list c that has two elements list a and list b
c = [a,b]
print(c)

[[10, 20, 30], [30, 60, 90]]


In [4]:
# list d contains the elements of integer lists a and b 
d = a + b
print(d)

[10, 20, 30, 30, 60, 90]


In [5]:
# list e contains the elements of integer lists a and b but with removal of all '30' integers
e = a + b
e.remove(30)
e.remove(30)
print(e)

[10, 20, 60, 90]


In [6]:
# list f contains the elements of integer lists a and b 
# with the removal of elements 10, 30, 30, 90
# with an insert of integer 40 at index 1 (2nd element of list)
f = a + b
f.remove(10)
f.remove(30)
f.remove(30)
f.remove(90)
f.insert(1, 40)
print(f)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [24]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

#hint attempt:
hint = sum(G[0])
print(hint)

# attempt 1:
# creating a list of the sums of each list element in G
answer1 = [sum(G[0]), sum(G[1]), sum(G[2]), sum(G[3])]
print(answer1)

# attempt 2 - final
# this answer will still work in the case G has more or less lists elements
answer2 = []
for list in G:
    answer2.append(sum(list))
print(answer2)

30
[30, 32, 34, 34]
[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [26]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [49]:
# attempt 1
# finding the substrings of s for 'all good' + ' country' + 'men'
answer1 = s[20:28] + s[60:68] + s[29:32]
print(answer1)

# attempt 2 - final
# splitting the string s into list of substrings using the default delimiter " "
# extracing target substrings to make the new phrase
# note that substring at index 15 has an extra '!' character, to remove it we can take the slice between 0 and 7
s_split = s.split()
print(s_split)
answer2 = s_split[5] + " " + s_split[6] + " " + (s_split[15])[0:7] + s_split[7]
print(answer2)

all good countrymen
['Now', 'is', 'the', 'time', 'for', 'all', 'good', 'men', 'to', 'come', 'to', 'the', 'aid', 'of', 'their', 'country!']
all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [57]:
a = "Sarah earns $96500 in a year"

# split the substrings of a
a_split = a.split()
print(a_split)

# b is using the original substrings of a
b = a_split[0] + " " + a_split[1] + " " + a_split[2] + " monthly"
print(b)

# c is using the original substrings of a but removing the incorrect value
c = a_split[0] + " " + a_split[1] + " " + a_split[2][0] + " monthly"
print(c)

# d has the final output string with the correct value type converted from float to string
d = a_split[0] + " " + a_split[1] + " " + a_split[2][0] + str(8041.67) + " monthly"
print(d)

['Sarah', 'earns', '$96500', 'in', 'a', 'year']
Sarah earns $96500 monthly
Sarah earns $ monthly
Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [78]:
# part 1
california = {
              "name": "CA",
              "pop_density": 239.1,
              "race":
               {"Prop White": 0.57,
               "Prop Afr Amer": 0.06,
               "Prop Asian": 0.07,
               "Prop Other": 0.22}
              ,
              "tenure":
               {"Owners": 7035371,
               "Renters": 5542127}
             }

newyork = {
              "name": "NY",
              "pop_density": 411.2,
              "race":
               {"Prop White": 0.65,
               "Prop Afr Amer": 0.15,
               "Prop Asian": 0.13,
               "Prop Other": 0.22}
              ,
              "tenure":
               {"Owners": 3897837,
               "Renters": 3419918}
             }
print(california)
print(newyork)

states = {
    "California": california,
    "NewYork": newyork,
}
print(states)

{'name': 'CA', 'pop_density': 239.1, 'race': {'Prop White': 0.57, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.07, 'Prop Other': 0.22}, 'tenure': {'Owners': 7035371, 'Renters': 5542127}}
{'name': 'NY', 'pop_density': 411.2, 'race': {'Prop White': 0.65, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}
{'California': {'name': 'CA', 'pop_density': 239.1, 'race': {'Prop White': 0.57, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.07, 'Prop Other': 0.22}, 'tenure': {'Owners': 7035371, 'Renters': 5542127}}, 'NewYork': {'name': 'NY', 'pop_density': 411.2, 'race': {'Prop White': 0.65, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}}


In [79]:
# part 2
states["Texas"]

KeyError: 'Texas'

In [80]:
# part 3
# googled 'how to print float as percentage python'
# https://stackoverflow.com/questions/5306756/how-to-print-a-percentage-value
whitePercentageInNY = format(states["NewYork"]["race"]["Prop White"], ".0%")
print(whitePercentageInNY)

65%


In [81]:
# part 4
print(states["NewYork"])
states["NewYork"]["race"]["Prop White"] = 0.64
print(states["NewYork"])

{'name': 'NY', 'pop_density': 411.2, 'race': {'Prop White': 0.65, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}
{'name': 'NY', 'pop_density': 411.2, 'race': {'Prop White': 0.64, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'tenure': {'Owners': 3897837, 'Renters': 3419918}}


In [89]:
# part 5
# find total population in CA
totalHouseholdPopulationCA = states["California"]["tenure"]["Owners"] + states["California"]["tenure"]["Renters"]
print(totalHouseholdPopulationCA)

# find decimal representation of % of renter households
renterPercentageOfHouseholds = states["California"]["tenure"]["Renters"] / totalHouseholdPopulationCA
print(renterPercentageOfHouseholds)

# format deicmal as percentage with 2 significant figures
renterPercentageOfHouseholdsFormatted = format(renterPercentageOfHouseholds, ".2%")
print(renterPercentageOfHouseholdsFormatted)

12577498
0.4406382732082327
44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [92]:
import numpy as np

In [98]:
# generate 4x4 matrix with all elements initialized to 3
a = np.full((4, 4), 3, dtype=int)
a

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [100]:
# generate random 4x4 matrix
b = np.random.rand(4,4)
b

array([[0.73625431, 0.46928929, 0.0736154 , 0.98626391],
       [0.12863631, 0.61025726, 0.98279299, 0.98222265],
       [0.85274064, 0.42214575, 0.79541977, 0.23332994],
       [0.42086502, 0.39115783, 0.7004153 , 0.19252619]])

In [102]:
# divide two matrices of matching dimensions
c = np.divide(a, b)
c

array([[ 4.07467901,  6.39264539, 40.75234228,  3.04178218],
       [23.32156486,  4.91595956,  3.05252483,  3.0542973 ],
       [ 3.51806854,  7.10655037,  3.77159347, 12.85732957],
       [ 7.12817622,  7.66953845,  4.28317314, 15.58229529]])

In [104]:
# flatten the matrix into a list and calcu
d = c.flatten()
print(np.min(d))
print(np.max(d))
print(np.median(d))
print(np.percentile(d, 90))

3.041782182797003
40.75234228273326
5.654302475620567
19.45193007535083


In [108]:
# find the sum column-wise (axis 0) then take the 2nd column (index 1)
columnWiseSum = np.sum(c, axis = 0)
print(columnWiseSum)
e = columnWiseSum[1]
print(e)

[38.04248863 26.08469377 51.85963372 34.53570435]
26.08469377069229
