## Assignment 1 | Data Types

Add code cells as needed for Zeyu Wu's answers. 

In [1]:
import numpy as np

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a = [10, 20, 30]
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [3]:
print([a,b])

[[10, 20, 30], [30, 60, 90]]


In [4]:
print(a+b)

[10, 20, 30, 30, 60, 90]


In [5]:
print([a[0], a[1]] + b[1:])

[10, 20, 60, 90]


In [6]:
print([y - x for x, y in zip(a, b)])

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [7]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
print([sum(sublist) for sublist in G])  # sum of each sublist using list comprehension

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [8]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [9]:
words = s.split() # filtered_words = [word for word in words if word in ['all', 'good', 'men', 'country!']] 
print(words[5], words[6], words[15].replace('!', '') + words[7])

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [10]:
a = "Sarah earns $96500 in a year"
words = a.split()
print(words[0], words[1], words[2][0] + "{:.2f}".format(float(a.split()[2][1:]) / 12) + " monthly")  # int(a.split()[2].strip("$")) / 12

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [11]:
CA = {
    "name": "California",
    "population density": 239.1,
    "race": {
        "white": 0.57,
        "african american": 0.06,
        "asian": 0.13,
        "other": 0.22
    },
    "tenure": {
        "owners": 7035371,
        "renters": 5542127
    }
}

NY = {
    "name": "New York",
    "population density": 411.2,
    "race": {
        "white": 0.65,
        "african american": 0.15,
        "asian": 0.07,
        "other": 0.22
    },
    "tenure": {
        "owners": 3897837,
        "renters": 3419918
    }
}

states = {"CA": CA, "NY": NY}

# Check if Texas is in the dictionary
if "TX" in states:
    print("Texas is in the state dictionary")
else:
    print("Texas is not in the state dictionary")

print("The percentage of White population in New York: " + "{:.0f}%".format(NY["race"]["white"] * 100))

NY["race"]["white"] = 0.64
white_population_NY = NY["race"]["white"] * 100
print(f"The percentage of White population in New York (Update): {white_population_NY:.0f}%")

print("The percentage of renters in California: " + "{:.2f}%".format(CA["tenure"]["renters"] / (CA["tenure"]["owners"] + CA["tenure"]["renters"]) * 100))


Texas is not in the state dictionary
The percentage of White population in New York: 65%
The percentage of White population in New York (Update): 64%
The percentage of renters in California: 44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [12]:
a = np.ones((4, 4)) * 3
print("Array a:\n", a)

Array a:
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [13]:
b = np.random.rand(4, 4)
print("Array b:\n", b)

Array b:
 [[5.04654663e-01 9.39083198e-01 4.18671111e-01 2.12934250e-01]
 [2.44667677e-01 7.63793602e-02 6.66328108e-01 9.45020029e-04]
 [8.85622649e-01 9.77731783e-01 3.18588648e-01 2.07397617e-01]
 [8.13560023e-01 2.66421079e-01 6.30522303e-01 4.33473997e-02]]


In [14]:
c = a / b  # c = np.divide(a, b)
print("Array c:\n", c)

Array c:
 [[5.94465923e+00 3.19460513e+00 7.16552902e+00 1.40888561e+01]
 [1.22615298e+01 3.92776267e+01 4.50228643e+00 3.17453589e+03]
 [3.38744724e+00 3.06832615e+00 9.41653136e+00 1.44649685e+01]
 [3.68749682e+00 1.12603703e+01 4.75796017e+00 6.92083037e+01]]


In [15]:
print("Min:", np.min(c))
print("Mean:", np.mean(c))
print("Max:", np.max(c))
print("Median:", np.median(c))
print("90th percentile:", np.percentile(c, 90))

Min: 3.0683261510545385
Mean: 211.26389924238475
Max: 3174.535891287291
Median: 8.291030193743929
90th percentile: 54.24296519278286


In [16]:
print("\nSum of second column:", np.sum(c[:, 1]))


Sum of second column: 56.80092830964976
