## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [1]:
# List of numbers 10, 20, and 30.
a = [10, 20, 30]

# List of numbers 30, 60, and 90.
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [5]:
# 1. [[10, 20, 30], [30, 60, 90]]
[a] + [b]

[[10, 20, 30], [30, 60, 90]]

In [6]:
# 2. [10, 20, 30, 30, 60, 90]
a + b

[10, 20, 30, 30, 60, 90]

In [12]:
# 3. [10, 20, 60, 90]
a[:2] + b[1:]

[10, 20, 60, 90]

In [21]:
# 4. [20, 40, 60]
[a[1]] + [a[0]+a[2]] + [b[1]]

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [53]:
# Compute sum of G to [30, 32, 34, 34]
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
[G[0][0]+G[0][1]+G[0][2]] + [G[1][0]+G[1][1]+G[1][2]] + [G[2][0]+G[2][1]+G[2][2]] + [G[3][0]+G[3][1]+G[3][2]]

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [55]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [99]:
# Turn the string below into 'all good countrymen'
s.split()[5] + " " + s.split()[6] + " " + s.split()[-1].strip("!")+s.split()[7]

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [140]:
# Print the following string: Sarah earns $8041.67 monthly
a = "Sarah earns $96500 in a year"
print(a.split()[0] + " " + a.split()[1] + " $8041.67 monthly")

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [228]:
# 1. Create dictionaries CA and NY with name, pop_density, race, and tenure
CA = {"name":"California", "pop_density": 239.1, "race":{"Prop White":0.57, "Prop Afr Amer":0.06, "Prop Asian":0.13, "Prop Other":0.22}, "tenure":{"Owners":7035371, "Renters":5542127}}
NY = {"name":"New York", "pop_density": 411.2, "race":{"Prop White":0.65, "Prop Afr Amer":0.15, "Prop Asian":0.07, "Prop Other":0.22}, "tenure":{"Owners":3897837, "Renters":3419918}}
# Make a nested dictionary of both dictionaries
states = {"CA":CA, "NY":NY}

# 2. Check if Texas is in our state dictionary
#states['TX']
# KeyError: 'TX'

# 3. Print white population in New York as a percentage
print(f"White population in New York as a percentage: {states['NY']['race']['Prop White']}%")

# 4. Update white population fraction to 0.64
states['NY']['race']['Prop White'] = 0.64
print(f"Updated white population fraction: {states['NY']['race']['Prop White']}%")

# 5. Print percentage of households renting in California
print(f"Percentage of households renting in California: {states['CA']['tenure']['Renters']/(states['CA']['tenure']['Owners'] + states['CA']['tenure']['Renters']) * 100:.2f}%")

White population in New York as a percentage: 0.65%
Updated white population fraction: 0.64%
Percentage of households renting in California: 44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [307]:
# Import Numpy 
import numpy as np
np.random.seed(123) 
# 1. Create array, a, in 4x4
a = np.zeros((4,4))
# Turn zeros to 3
a[:] = 3
a

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [308]:
# 2. Create a 4x4 of elements from a random distribution
b = np.random.uniform(0, 10, 16).reshape(4,4)
b

array([[6.96469186, 2.86139335, 2.26851454, 5.51314769],
       [7.1946897 , 4.2310646 , 9.80764198, 6.84829739],
       [4.80931901, 3.92117518, 3.43178016, 7.29049707],
       [4.38572245, 0.59677897, 3.98044255, 7.37995406]])

In [309]:
# 3. Create c which divides a by b
c = a/b
c

array([[0.43074411, 1.04844026, 1.3224513 , 0.54415375],
       [0.4169742 , 0.70904141, 0.30588392, 0.43806509],
       [0.62378894, 0.76507676, 0.87418187, 0.41149458],
       [0.68403782, 5.02698682, 0.75368504, 0.4065066 ]])

In [321]:
# 4. Prin min, max, mean, median, 90th percentile of c
print(f"Min: {c.min()}, Max: {c.max()}, Mean: {c.mean()}, Median: {np.median(c)}, 90th Percentile: {np.percentile(c, 90)}")

Min: 0.3058839224495757, Max: 5.026986824999795, Mean: 0.9225945291721893, Median: 0.6539133764535519, 90th Percentile: 1.18544578293742


In [333]:
# 5. Print sum of second column in c
print(c[1])
print(f"Sum of second column in c: {sum(c[1])}")

[0.4169742  0.70904141 0.30588392 0.43806509]
Sum of second column in c: 1.8699646210082532
