## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [23]:
a=[10,20,30]
b=[30,60,90]
#print(a)

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [24]:
output1=[a,b]
print (output1)
output2=[a+b]
print (output2)
output3=a[:2]+b[1:]
print (output3)

[[10, 20, 30], [30, 60, 90]]
[[10, 20, 30, 30, 60, 90]]
[10, 20, 60, 90]


In [32]:
output4=a[:2]+b[1:]
output4.remove(10)
output4.remove(90)
#insert below wont know where to insert
#1 specifies the index where to insert 40
output4.insert(1,40)
print (output4)

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [34]:
G=[[13,9,8],[14,6,12],[10,13,11],[7,18,9]]

In [35]:
sum_of_first_sublist = sum(G[0])

In [36]:
sum_of_second_sublist = sum(G[1])

In [37]:
sum_of_third_sublist = sum(G[2])

In [38]:
sum_of_fourth_sublist = sum(G[3])

In [41]:
#Need to assign an object (in this case c)
c=[sum(G[0]), sum(G[1]), sum(G[2]),sum(G[3])]
print(c)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [43]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [47]:
#strings also have indexes, N=0, space is also an index
#we're splitting the list s, into a list of substrings, we have split s by a deliminator here which is a space
s2=s.split()
print(s2)
#default here is the space

['Now', 'is', 'the', 'time', 'for', 'all', 'good', 'men', 'to', 'come', 'to', 'the', 'aid', 'of', 'their', 'country!']


In [68]:
#Now each word is an index
#we now need all, good, country, men from the above
#By moving s2 [7] after 15, we get countrymen
s3=s2[5]+s2[6]+s2[15]+s2[7]
#to add a space (deliminator - boundary beetween two characters) between, add a double quotation and
s3=s2[5]+ " " + s2[6]+  " "+ s2[15]+s2[7]
#in order to remove !, we are treating ! as the 7th index of country
s3=s2[5]+ " " + s2[6]+  " "+ s2[15] [:7]+s2[7]
print(s3)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [87]:
a = "Sarah earns $96500 in a year"
a2=a.split()
print (a2)
a3=a2[0] + a2[1] + a2[2]
print (a3)
#we now add a space between each like above
a3=a2[0] + " " + a2[1] + " " + a2[2]
print (a3)
#In order to change the number and keep only the dollar sign
a3=a2[0] + " " + a2[1] + " " + a2[2][0]
print (a3)
#string is making integers strings, words are already strings
a3=a2[0] + " " + a2[1] + " " + a2[2][0] + str(8041.67) + " monthly"

['Sarah', 'earns', '$96500', 'in', 'a', 'year']
Sarahearns$96500
Sarah earns $96500
Sarah earns $


In [88]:
a3=a2[0] + " " + a2[1] + " " + a2[2][0] + str(8041.67) + " monthly"
print (a3)

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [ ]:
# a dictionary lists in categories
# States/Pop Dens etc are keys
# CA And NY are values in the key
# Key-Value Pair (States-CA)
# Keys are immutable , Values are mutable

In [ ]:
#To create an empty dictionary
#{} creates a dictionary - first way
newd={}
#creates a dictionary - second way through a function
newd=dict()

In [103]:
california={
            'Name':'CA', 
            'Pop Density': 239.1, 
            'Race': {'Prop White':0.57, 
                     'Prop Afr Amer': 0.06, 
                     'Prop Asian': 0.13, 
                     'Prop Other': 0.22}, 
            'Tenure': {'Owners':7035371, 
                       'Renters':5542127 }
           }
print(california)

{'Name': 'CA', 'Pop Density': 239.1, 'Race': {'Prop White': 0.57, 'Prop Afr Amer': 0.06, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'Tenure': {'Owners': 7035371, 'Renters': 5542127}}


In [108]:
newyork={
         'Name': 'NY',
         'Pop Density': 411.2,
         'Race':{'Prop White': 0.65,
                 'Prop Afr Amer': 0.15,
                 'Prop Asian': 0.13,
                 'Prop Other': 0.22},
        'Tenure': {'Owners': 3897837,'Renters': 3419918}
         }

print(newyork)

{'Name': 'NY', 'Pop Density': 411.2, 'Race': {'Prop White': 0.65, 'Prop Afr Amer': 0.15, 'Prop Asian': 0.13, 'Prop Other': 0.22}, 'Tenure': {'Owners': 3897837, 'Renters': 3419918}}


In [109]:
states= {'California': california,
        'NewYork': newyork}

In [98]:
states['Texas']

NameError: name 'states' is not defined

In [138]:
#to print float as percentage
popwhiteNY=format(states["NewYork"]['Race']['Prop White'], '.0%')
print(popwhiteNY)

65%


In [144]:
#to change value of white percentage
newyork['Race']['Prop White']=0.64
prop_white_percentage = newyork['Race']['Prop White'] * 100
#to get no decimal places, mention 0f
print("{:.0f}%".format(prop_white_percentage))

64%


In [145]:
#Part 5
renter_percentage = (california['Tenure']['Renters'] / (california['Tenure']['Owners'] + california['Tenure']['Renters'])) * 100
#to get two decimal places, mention 2f
print("{:.2f}%".format(renter_percentage))

44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [1]:
import numpy as np

In [2]:
a=np.full((4,4),3)
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [3]:
#to be honest, I used ChatGPT for this
b=np.random.rand(4,4)
print(b)

[[0.7887878  0.774923   0.58658122 0.29087752]
 [0.57823399 0.25689974 0.94984414 0.29550008]
 [0.44986821 0.39134659 0.42450968 0.28101816]
 [0.10121226 0.72375    0.95847127 0.79131118]]


In [4]:
c = np.divide(a, b)
print(c)

[[ 3.80330427  3.8713524   5.11438126 10.31361924]
 [ 5.18821106 11.67770723  3.15841292 10.15228167]
 [ 6.66861964  7.66583905  7.06697674 10.67546671]
 [29.64067658  4.1450777   3.12998427  3.79117608]]


In [9]:
c_min = np.min(c)
print("Minimum value of c: {:.2f}".format(c_min))
c_mean = np.mean(c)
print("Mean value of c: {:.2f}".format(c_mean))
c_max=np.max(c)
print("Maximum value of c: {:.2f}".format(c_max))
c_median=np.median(c)
print("Median value of c: {:.2f}".format(c_median))
c_pct_90 = np.percentile(c, 90)
print("90th Percentile value of c: {:.2f}".format(c_pct_90))

Minimum value of c: 3.13
Mean value of c: 7.88
Maximum value of c: 29.64
Median value of c: 5.93
90th Percentile value of c: 11.18
