## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [1]:
a = [10, 20, 30]
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [2]:
[a,b]

[[10, 20, 30], [30, 60, 90]]

In [3]:
a + b

[10, 20, 30, 30, 60, 90]

In [4]:
[a[0], a[1], b[1], b[2]]

[10, 20, 60, 90]

In [11]:
[a[1], b[1]//2+10, b[2]//3*2] 

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [16]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]] 

sums = []
for list in G:
    sums.append(sum(list))
    
print(sums)

[30, 32, 34, 34]


### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [52]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [57]:
result = s[20:29] + 'countrymen' 
print(result)

all good countrymen


### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [94]:
a = "Sarah earns $96500 in a year"

# Step 1
salary = int(a[13:18]) # Extract salary amount 
print(salary)

96500


In [95]:
#step 2

monthly = round(salary/12,2)
print (monthly)

8041.67


In [97]:
#step 3
a = a[:a.index('$')+1] + str(monthly) + ' monthly'

print(a)

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [134]:
#part 1
california = {
               "name": "CA",
               "pop_density": 239.1,
               "race": 
                {"prop_white": 0.57,
                 "prop_black": 0.06,  
                 "prop_asian": 0.13,
                 "prop_other": 0.22}
                ,
                "tenure": 
                {"owners": 7035371,
                 "renters": 5542127}
                }

newyork = {
   "name": "NY", 
   "pop_density": 411.2,
   "race": {
       "prop_white": 0.65,
       "prop_black": 0.15,  
       "prop_asian": 0.07,
       "prop_other": 0.22}
    ,
    "tenure": {
       "owners": 3897837, 
       "renters": 3419918}
    }

print(california)
print(newyork)
    
states = {
    "California": california,
    "NewYork": newyork
}
print(states)

{'name': 'CA', 'pop_density': 239.1, 'race': {'prop_white': 0.57, 'prop_black': 0.06, 'prop_asian': 0.13, 'prop_other': 0.22}, 'tenure': {'owners': 7035371, 'renters': 5542127}}
{'name': 'NY', 'pop_density': 411.2, 'race': {'prop_white': 0.65, 'prop_black': 0.15, 'prop_asian': 0.07, 'prop_other': 0.22}, 'tenure': {'owners': 3897837, 'renters': 3419918}}
{'California': {'name': 'CA', 'pop_density': 239.1, 'race': {'prop_white': 0.57, 'prop_black': 0.06, 'prop_asian': 0.13, 'prop_other': 0.22}, 'tenure': {'owners': 7035371, 'renters': 5542127}}, 'NewYork': {'name': 'NY', 'pop_density': 411.2, 'race': {'prop_white': 0.65, 'prop_black': 0.15, 'prop_asian': 0.07, 'prop_other': 0.22}, 'tenure': {'owners': 3897837, 'renters': 3419918}}}


In [135]:
#part 2
states["Texas"]

KeyError: 'Texas'

In [136]:
#part 3; not sure how to add the % sign, asked google/chat gpt how to format 
white_pct_ny = states["NewYork"]["race"]["prop_white"] * 100
print(white_pct_ny)

65.0


In [137]:
#chat gpt recommended this code
print(f'{white_pct_ny:.0f}%')

65%


In [138]:
#part 4 
states["NewYork"]["race"]["prop_white"] = 0.64

# Print updated percentage
white_pop_ny = states["NewYork"]["race"]["prop_white"] * 100  
print(f'{white_pop_ny:.0f}%')

64%


In [143]:
#Part 5: Print the percentage of households that are renters in California, with two decimal places
# Get tenure totals  
total_households_ca = CA["tenure"]["owners"] + CA["tenure"]["renters"]
print(total_households_ca)

# Calculate renter percentage
renter_pct_ca = CA["tenure"]["renters"] / total_households_ca
print(renter_pct_ca)

# Print with 2 decimal places  
print(f'{renter_pct_ca:.2%}')

12577498
0.4406382732082327
44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [103]:
import numpy as np

# Create array a with value 3 everywhere
a = np.full((4, 4), 3)
print("Array a:\n", a)

Array a:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [104]:
# Create array b with elements drawn from a uniform random distribution
b = np.random.rand(4, 4)
print("\nArray b:\n", b)


Array b:
 [[0.3586067  0.4449874  0.71216387 0.31564201]
 [0.61853415 0.7415754  0.28492296 0.8165673 ]
 [0.37069823 0.50282783 0.61565189 0.2306261 ]
 [0.93724934 0.16408508 0.66989684 0.98432762]]


In [105]:
# Create array c by dividing a by b
c = a / b
print("\nArray c:\n", c)


Array c:
 [[ 8.36571104  6.74176391  4.21251362  9.50443826]
 [ 4.8501768   4.04544166 10.5291619   3.67391643]
 [ 8.09283599  5.96625684  4.8728836  13.00806802]
 [ 3.20085581 18.28319838  4.47830144  3.04776573]]


In [106]:
# Compute and print min, mean, max, median, and 90th percentile values of c
print("\nMin:", np.min(c))
print("Mean:", np.mean(c))
print("Max:", np.max(c))
print("Median:", np.median(c))
print("90th Percentile:", np.percentile(c, 90))


Min: 3.047765727567014
Mean: 7.05458058956047
Max: 18.28319838339378
Median: 5.419570218960465
90th Percentile: 11.768614960514228


In [107]:
# Compute and print the sum of the second column in c
print("\nSum of the second column in c:", np.sum(c[:, 1]))


Sum of the second column in c: 35.036660792788645
