## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [2]:
a = [10,20,30]
b = [30,60,90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [6]:
c = [a,b]
c

[[10, 20, 30], [30, 60, 90]]

In [9]:
d = a+b
d

[10, 20, 30, 30, 60, 90]

In [10]:
e = [d[0],d[1],d[4],d[5]]
e

[10, 20, 60, 90]

In [13]:
f = [a[0]*2, a[1]*2, a[2]*2]
f

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [16]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]
sum0 = G[0][0]+G[0][1]+G[0][2]
sum1 = G[1][0]+G[1][1]+G[1][2]
sum2 = G[2][0]+G[2][1]+G[2][2]
sum3 = G[3][0]+G[3][1]+G[3][2]

sumG = [sum0, sum1, sum2, sum3]
sumG

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [ ]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [26]:
s = 'Now is the time for all good men to come to the aid of their country !'
s1 = str.split(s," ")
s2 = [s1[5],s1[6],s1[15]]
s = str.join(' ', s2)+s1[7]
s

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [87]:
a = "Sarah earns $96500 in a year"
b = a.split('$')[1]
c = b.split(' ')[0]
c_int = int(c)
c_month = c_int/12
c_month
a1 = a.split('$')[0] + '$' + str(c_month) + ' monthly'
print(a1)

#combined
income = round(int(a.split('$')[1].split(' ')[0])/12,2)
a_new = a.split('$')[0] + '$' + str(income) + ' monthly'
print(a_new)

Sarah earns $8041.666666666667 monthly
Sarah earns $8041.67 monthly


In [88]:
print(a.split('$')[0] + '$' + str(round(int(a.split('$')[1].split(' ')[0])/12,2)) + ' monthly')

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [72]:
CA = { 
      'name:': 'California', 
      'pop_density': 239.1, 
      'race':{'White': 0.57, 'African American': 0.06, 'Asian': 0.13, 'Other': 0.22},
      'tenure': {'Owners': 7035371, 'Renters': 5542127}
      }
NY = { 
      'name:': 'New York', 
      'pop_density': 411.2, 
      'race':{'White': 0.65, 'African American': 0.15, 'Asian': 0.07, 'Other': 0.22},
      'tenure': {'Owners': 3897837, 'Renters': 3419918}
      }
states = {'CA': CA, 'NY':NY}

#checking if Texas is in states
print('TX' in states)

#printing White population in NY
NY_W_percent = round(NY['race']['White']*100)
print('Percentage of White population in New York is ' +str(NY_W_percent)+'%')

#updating the data 
NY['race']['White']= 0.64
NY_W_percent = round(NY['race']['White']*100)
print('Percentage of White population in New York is ' +str(NY_W_percent)+'%')

#percentage of renters in California
CA_R_percent = round(CA['tenure']['Renters']/(CA['tenure']['Renters']+CA['tenure']['Owners'])*100,2)
print('Percentage of renters in California is ' +str(CA_R_percent)+'%')

False
Percentage of White population in New York is 65%
Percentage of White population in New York is 64%
Percentage of renters in California is 44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [76]:
import numpy as n
a = n.full((4, 4), 3)
print("Array a:")
print(a)

Array a:
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [86]:
b = n.random.rand(4, 4)
print("Array b:")
print(b)

Array b:
[[0.35188263 0.17539759 0.99954108 0.82459533]
 [0.54117361 0.17107929 0.94989731 0.12641302]
 [0.07458886 0.94787351 0.22712004 0.84833833]
 [0.82529033 0.35013504 0.8788615  0.36876033]]


In [85]:
c = n.divide(a, b)
print("Array c:")
print(c)

Array c:
[[  3.74247454   6.44192772   3.13975227  21.97624523]
 [  5.23171936   3.50457547   7.45214477   3.20276645]
 [116.37329391 174.04918853   5.40653678   3.57112938]
 [ 21.81730939   3.07334921   5.84374346   5.72692465]]


In [80]:
print("\nStatistics of c:")
print("Minimum:", n.min(c))
print("Mean:", n.mean(c))
print("Maximum:", n.max(c))
print("Median:", n.median(c))
print("90th percentile:", n.percentile(c, 90))


Statistics of c:
Minimum: 3.117265180584601
Mean: 15.02349030939922
Maximum: 134.46989741171177
Median: 7.340182631641727
90th percentile: 12.799075727625356


In [84]:
sum_second_column = n.sum(c[:, 1])
print("Sum of the second column in c:", sum_second_column)

Sum of the second column in c: 161.41989848421107
