## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [3]:
a = [10, 20, 30]
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [4]:
[a,b]

[[10, 20, 30], [30, 60, 90]]

In [5]:
a + b

[10, 20, 30, 30, 60, 90]

In [7]:
a[0:2]+b[1:]

[10, 20, 60, 90]

In [9]:
[b[i]-a[i] for i in range (3)]

[20, 40, 60]

### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [2]:
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

In [3]:
sum(G[0])

30

In [5]:
[sum(G[i]) for i in range (4)]

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [9]:
s = 'Now is the time for all good men to come to the aid of their country!'

In [13]:
x = s.replace(' ', ',').strip('!')
print(x)

Now,is,the,time,for,all,good,men,to,come,to,the,aid,of,their,country


In [14]:
x = str.split(x, ",")
print(x)

['Now', 'is', 'the', 'time', 'for', 'all', 'good', 'men', 'to', 'come', 'to', 'the', 'aid', 'of', 'their', 'country']


In [18]:
x[5] + " " + x[6]+ " "+ x[15]+ x[7]

'all good countrymen'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [19]:
a = "Sarah earns $96500 in a year"

In [28]:
x = a.replace(' ', ',').replace("$", "")
print(x)

Sarah,earns,96500,in,a,year


In [29]:
x = str.split(x, ",")
print(x)

['Sarah', 'earns', '96500', 'in', 'a', 'year']


In [35]:
yearly = int(x[2])
print(yearly)

96500


In [41]:
monthly = (yearly/12)
monthly = round(monthly, 2)
print(monthly)

8041.666666666667
8041.67


In [49]:
output = x[0] + " " + x[1] + " $" + str(monthly) + " "+ "monthly"
print(output)

Sarah earns $8041.67 monthly


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [67]:
CA = {'name':'CA', 'population density': 239.1, 'race' : {'White':0.57, 'Afr Amer': 0.06, 'Asian': 0.13, 'Other':0.22}, 'tenure' : {'Owners':7035371, 'Renters':5542127 }}
NY = {'name':'NY', 'population density': 411.2, 'race' : {'White':0.65, 'Afr Amer': 0.15, 'Asian': 0.07, 'Other':0.22}, 'tenure' : {'Owners':3897837, 'Renters':3419918 }}
states = {'CA' : CA, 'NY' : NY}

KeyError: 'TX'

In [75]:
if 'TX' in states:
    print("True")
else:
    print("False")


False


In [81]:
print(str(int(states['NY']['race']['White'] * 100)) + "%")

65%


In [84]:
states['NY']['race']['White'] = 0.64
print(str(int(states['NY']['race']['White'] * 100)) + "%")

64%


In [90]:
r = states['CA']['tenure']['Renters']
total = r + states['CA']['tenure']['Owners']

rpct = round(r/total * 100, 2)
print(str(rpct) + "%")

44.06%


### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [91]:
import numpy as np

In [92]:
a = np.full((4, 4), 3)
print("Array a:\n", a)

Array a:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [93]:
b = np.random.rand(4, 4)
print("\nArray b:\n", b)


Array b:
 [[0.28241063 0.19582246 0.1226557  0.36676949]
 [0.88235823 0.45527278 0.60103304 0.74938295]
 [0.08957036 0.83008818 0.515466   0.44852288]
 [0.06832199 0.1830105  0.73307172 0.25116394]]


In [94]:
c = np.divide(a, b)
print("\nArray c:\n", c)


Array c:
 [[10.62282957 15.31999985 24.45870836  8.17952446]
 [ 3.39997963  6.58945604  4.99140615  4.00329363]
 [33.4932238   3.61407388  5.81997652  6.68862202]
 [43.90972487 16.39250184  4.092369   11.94438976]]


In [96]:
min_c = np.min(c)
mean_c = np.mean(c)
max_c = np.max(c)
median_c = np.median(c)
percentile_90_c = np.percentile(c, 90)

print("\nStatistics of array c:")
print("Min:", min_c)
print("Mean:", mean_c)
print("Max:", max_c)
print("Median:", median_c)
print("90th Percentile:", percentile_90_c)


Statistics of array c:
Min: 3.3999796307098324
Mean: 12.720004961673895
Max: 43.90972487494793
Median: 7.434073241010095
90th Percentile: 28.975966081674372


In [97]:
sum_second_column = np.sum(c[:, 1])
print("\nSum of the second column in array c:", sum_second_column)


Sum of the second column in array c: 41.91603160591019
